name: Wilfried Woivré & Azure
description: Azure, Cloud, Service Fabric, Serverless, Container

url : "https://wilfriedwoivre.github.io"

baseurl: ""

github: "wilfridwoivre/wilfriedwoivre.github.io"
gitlab : ''

gaacount: ''

comments: false

isso: ''
disqs: ''

permalink: '/:year/:month/:title'
category_layout: categories.html

paginate: 5

highlighter: rouge
markdown: kramdown
plugins: 
  - jekyll-paginate
  - jekyll-category-pages
  - jekyll-feed

exclude: ['README.md', 'LICENSE']