author: Wilfried Woivré
name: Wilfried Woivré & Azure
description: Azure, Cloud, Service Fabric, Serverless, Container, ...

url : "http://github.woivre.fr"

baseurl: ""

github: "wilfriedwoivre"
gitlab : ''

gaacount: ''

comments: false

isso: ''
disqs: ''

permalink: '/:year/:month/:title'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      permalink: '/blog/:year/:month/:title'

paginate: 5

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins: 
  - jekyll-paginate
  - jekyll-feed

exclude: ['README.md', 'LICENSE']